In [1]:
import numpy as np

### Question 1

In [13]:
def feval(w,a):
    z1 = a[0]*w[0]*w[1]
    z2 = a[1]*w[0]+a[2]*(w[1]**2)
    J = z1*np.exp(z1*z2)
    first = z1*z2*np.exp(2*z1*z2)
    second = (z1**2)*np.exp(z1*z2)
    dJ_1 = first*a[0]*w[1]+second*a[1]
    dJ_2 = first*a[0]*w[0]+second*2*a[2]*w[1]
    dJ = np.array([dJ_1,dJ_2])
    return J,dJ

In [14]:
w = [1,2]
a = [1,2,3]
J, dJ = feval(w,a)

In [15]:
J

2892514128582.95

In [16]:
dJ

array([1.17132932e+26, 5.85664659e+25])

### Question 2

In [19]:
np.array([[1,2],[2,3],[3,4]])

array([[1, 2],
       [2, 3],
       [3, 4]])

In [26]:
def Jeval(w,b,X,y):
    y_hat = X.dot(w)+b
    J = np.sum((np.log(y)[:,None]-np.log(y_hat)[:,None])**2,axis = 0)
    Jgradw = X.T.dot(-2*(np.log(y)[:,None]-np.log(y_hat)[:,None])/(y_hat[:,None]))
    Jgradb = -2*(np.log(y)[:,None]-np.log(y_hat)[:,None])/(y_hat[:,None])
    return J,Jgradw,Jgradb

In [27]:
w = [1,2]
b = 1
X = np.array([[1,2],[2,3],[3,4]])
y = np.array([1,2,3])
J,Jgradw,Jgradb = Jeval(w,b,X,y)

In [28]:
J

array([7.39446287])

In [29]:
Jgradw

array([[1.95887918],
       [3.12142082]])

In [30]:
Jgradb

array([[0.59725316],
       [0.33423942],
       [0.23104906]])

### Question 3

In [44]:
def Jeval(w,X,y):
    z = X.dot(w)
    J = np.sum((y[:,None]-z[:,None])**2,axis = 0)
    Jgrad0 = np.sum(2*(y[:,None]-(1/z)[:,None])/((z**2)[:,None]),axis = 0)
    Jgradj = (X[:,1:]).T.dot(2*(y[:,None]-(1/z)[:,None])/((z**2)[:,None]))
    print(Jgrad0)
    print('\n')
    print(Jgradj)
    Jgrad = np.vstack((Jgrad0,Jgradj))
    return J,Jgrad

In [45]:
w = [1,1,2]
X = np.array([[1,2,4],[1,3,4]])
y = np.array([1,2])
J,Jgrad = Jeval(w,X,y)

[0.04164667]


[[0.1099137 ]
 [0.16658667]]


In [46]:
J

array([200])

In [47]:
Jgrad

array([[0.04164667],
       [0.1099137 ],
       [0.16658667]])

### Question 4

In [97]:
def Jeval(a,b,X,y):
    z = (np.exp(-1/2*((X-b[None,:])**2))).dot(a[:,None])
    Jgrada = (np.exp(-1/2*((X-b[None,:])**2))).T.dot((np.exp(z)/(1+(np.exp(z))))-y[:,None])
    Jgradb = ((np.exp(-1/2*((X-b[None,:])**2)))*(X-b[None,:])).T.dot((np.exp(z)/(1+(np.exp(z))))-y[:,None])
    return J,Jgrada,Jgradb

In [98]:
a = np.array([1,2,3])
b = np.array([2,3,4])
y = np.array([1,0])
x = np.array([[5,7,9],[2,4,6]])
J,Jgrada,Jgradb = Jeval(a,b,X,y)

In [99]:
J

array([200])

In [100]:
Jgrada

array([[0.59945498],
       [0.99148409],
       [0.98833418]])

In [101]:
Jgradb

array([[-0.59945498],
       [ 0.00485557],
       [ 0.        ]])

### Question 7

In [ ]:
def Jeval(X,y):
    z = (X.T.dot(P)).dot(X)
    J = np.sum(z/(y[:,None])-np.log(z),axis = 0)
    Jgrad = ((1/y)[:,None] - 1/z).dot(X.T.dot(X))
    return J,Jgrad