In [1]:
import numpy as np

Question 1

In [2]:
X = np.array([[3,2,1],[2,4,5],[1,2,3],[0,2,5]])
X

array([[3, 2, 1],
       [2, 4, 5],
       [1, 2, 3],
       [0, 2, 5]])

In [3]:
sample_mean=np.mean(X,axis = 0)
sample_mean

array([1.5, 2.5, 3.5])

In [4]:
X_demean = X-sample_mean[None,:]
X_demean

array([[ 1.5, -0.5, -2.5],
       [ 0.5,  1.5,  1.5],
       [-0.5, -0.5, -0.5],
       [-1.5, -0.5,  1.5]])

In [5]:
Q = X_demean.T.dot(X_demean)/4
Q

array([[ 1.25,  0.25, -1.25],
       [ 0.25,  0.75,  0.75],
       [-1.25,  0.75,  2.75]])

In [6]:
eig_val, eig_vec = np.linalg.eig(Q)

In [7]:
eig_val

array([3.56166464, 1.1733803 , 0.01495506])

In [8]:
eig_vec

array([[-0.45056922, -0.66677184, -0.59363515],
       [ 0.19247228, -0.72187235,  0.66472154],
       [ 0.87174641, -0.18524476, -0.45358856]])

In [9]:
alpha = X_demean.dot(eig_vec)
alpha

array([[-2.95145599, -0.17610969, -0.0888421 ],
       [ 1.37104342, -1.69406159,  0.0198819 ],
       [-0.30682473,  0.78694448,  0.19125108],
       [ 1.8872373 ,  1.0832268 , -0.12229089]])

In [10]:
p = 3
alpha_v = []
for i in range(4):
    result = 0
    for j in range(p):
        result += alpha[i][j] * eig_vec[:,j]
    alpha_v.append(result)

reconstruct_X = alpha_v + sample_mean[None,:]
reconstruct_X

array([[ 3.00000000e+00,  2.00000000e+00,  1.00000000e+00],
       [ 2.00000000e+00,  4.00000000e+00,  5.00000000e+00],
       [ 1.00000000e+00,  2.00000000e+00,  3.00000000e+00],
       [-2.22044605e-16,  2.00000000e+00,  5.00000000e+00]])

In [11]:
np.sum((X-reconstruct_X)**2)

6.803925307531227e-30

In [12]:
p = 2
alpha_v_2 = []
for i in range(4):
    result = 0
    for j in range(p):
        result += alpha[i][j] * eig_vec[:,j]
    alpha_v_2.append(result)

reconstruct_X_2 = alpha_v_2 + sample_mean[None,:]
reconstruct_X_2

array([[ 2.94726021,  2.05905526,  0.95970224],
       [ 2.0118026 ,  3.98678407,  5.0090182 ],
       [ 1.11353336,  1.87287129,  3.0867493 ],
       [-0.07259617,  2.08128939,  4.94453025]])

In [13]:
np.sum((X-reconstruct_X_2)**2)

0.05982024573122595

In [14]:
np.sum((alpha[:,-1])**2)

0.059820245731225984

Question 3

In [ ]:
Xtr, Xts, ytr, yts = train_test_split(X, y, test_size=0.25)

In [ ]:
npc_test = [25,50,75,100,200]
acc = np.zeros((len(npc_test),))


for i0, npc in enumerate(npc_test):
    
    # Fit PCA on the training data
    pca = PCA(n_components=npc)
    mu,V = pca(Xtr)

    # Transform the training and test
    Ztr = V.T.dot(Xtr-mu)
    Zts = V.T.dot(Xts-mu)
    
    clf = Classifier()
    clf.fit(Ztr,ytr)
    yhat = clf.predict(Zts)
    acc_current = np.mean(yhat==yts)
    acc[i0] = acc_current

In [ ]:
optimal_index = np.argmax(acc)
optimal_npc = npc_test[optimal_index]
optimal_acc = acc[optimal_index]

Question 4

In [ ]:
shape = (1000, 28*28)
nc = 5

In [ ]:
Y = reshape(X, shape)
pca = PCA(n_components = nc)

Y_tr = Y[0:500,:]
Y_ts = Y[500::,:]
pca.fit(Y_tr)
Z = pca.transform(Y_ts)
Yhat = pca.inverse_transform(Z)

Question 5

In [ ]:
Xmean = np.mean(X, axis = 0)
Xs = X-Xmean[None,:]
A = Xs/np.sqrt(len(X))
U,s,Vtr = svd(Xs, full_matrices = False)

In [ ]:
n_dim = (np.shape(X))[1]
i = n_dim
pov = []

while(i>0):
    si = s[0:i-1]
    lam = si**2
    PoV = np.cumsum(lam)/np.sum(lam)
    pov.append(PoV)
    i-=1


In [ ]:
mini_npc = (np.where(pov>=0.9))[0][-1]

In [ ]:
Ahat = (U[:,0:mini_npc]*s[None,0:mini_npc]).dot(Vtr[0:mini_npc,:])
Xs_hat = Ahat*np.sqrt(len(X))
Xhat = Xs_hat + Xmean[None,:]