In [174]:
import numpy as np

Question (a)

In [175]:
X = np.arange(9).reshape(3,3)
print('X:\n'+str(X))
beta = np.array([2,4,6])
print('\nbeta:\n'+str(beta))

X:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

beta:
[2 4 6]


In [176]:
n = X.shape[0]
yhat = np.zeros(n)
for i in range(n):
    yhat[i] = beta[0]*X[i,0] + beta[1]*X[i,1] + beta[2]*X[i,1]*X[i,2]
yhat

array([ 16., 142., 376.])

In [177]:
X[:,2][:,None]=X[:,2][:,None]*X[:,1][:,None]
np.sum(X*beta[None,:],axis=1)

array([ 16, 142, 376])

Question (b)

In [178]:
x = np.arange(1,5)
print('x\n'+str(x))
alpha = np.array([2,4,6])
print('\nalpha\n'+str(alpha))
beta = np.array([1,3,5])
print('\nbeta\n'+str(beta))

x
[1 2 3 4]

alpha
[2 4 6]

beta
[1 3 5]


In [179]:
n = len(x)
m = len(alpha)
yhat = np.zeros(n)
for i in range(n):
    for j in range(m):
        yhat[i] += alpha[j]*np.exp(-beta[j]*x[i])
yhat

array([0.97533484, 0.28085797, 0.10006961, 0.03665587])

In [180]:
np.sum(np.exp(-x[:,None]*beta[None,:])*alpha[None,:],axis=1)

array([0.97533484, 0.28085797, 0.10006961, 0.03665587])

Question (c)

In [181]:
x = np.arange(8).reshape(4,2)
y = np.arange(3,9).reshape(3,2)
print('x\n'+str(x))
print('\ny\n'+str(y))

x
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

y
[[3 4]
 [5 6]
 [7 8]]


In [182]:
n,d = x.shape
m,d = y.shape
dist = np.zeros((n,m))
for i in range(n):
    for j in range(m):
        for k in range(d):
            dist[i,j] += (x[i,k]-y[j,k])**2
dist

array([[18., 50., 98.],
       [ 2., 18., 50.],
       [ 2.,  2., 18.],
       [18.,  2.,  2.]])

In [183]:
np.sum((x[:,None,:]-y[None,:,:])**2, axis = 2)

array([[18, 50, 98],
       [ 2, 18, 50],
       [ 2,  2, 18],
       [18,  2,  2]])